version: 2.1

jobs:
    build_and_test:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: make install
            - run: make build
            - run: make test

workflows:
    build:
        jobs:
            - build_and_test
